import type { Lesson } from "./types";

const CODE = [
  "function greet(name) {",
  '  const msg = "hi " + name;',
  "  console.log(msg);",
  "}",
  "",
  "function main() {",
  '  greet("vim");',
  "}",
].join("\n");

export const lesson: Lesson = {
  id: "05-line-navigation",
  title: "Line Navigation (0 ^ $ gg G)",
  section: "Motions",
  order: 5,
  steps: [
    {
      kind: "explanation",
      text: "Within a line: `0` jumps to column 0, `^` to the first non-blank character, `$` to the end of the line. Across the file: `gg` jumps to the first line, `G` to the last line, and `{n}G` to line n (e.g. `6G` for line 6).",
    },
    {
      kind: "challenge",
      id: "05-dollar",
      instruction: "Jump to the end of the line with `$`.",
      startText: CODE,
      startCursor: { line: 0, col: 0 },
      targetText: CODE,
      targetCursor: { line: 0, col: 21 },
      par: 1,
      hint: "$",
    },
    {
      kind: "challenge",
      id: "05-zero",
      instruction: "Jump to column 0 with `0`.",
      startText: CODE,
      startCursor: { line: 2, col: 10 },
      targetText: CODE,
      targetCursor: { line: 2, col: 0 },
      par: 1,
      hint: "0",
    },
    {
      kind: "challenge",
      id: "05-caret",
      instruction: "Jump to the first non-blank character of this indented line with `^`.",
      startText: CODE,
      startCursor: { line: 1, col: 26 },
      targetText: CODE,
      targetCursor: { line: 1, col: 2 },
      par: 1,
      hint: "^ (0 would land on the leading space)",
    },
    {
      kind: "challenge",
      id: "05-G",
      instruction: "Jump to the last line with `G`.",
      startText: CODE,
      startCursor: { line: 0, col: 0 },
      targetText: CODE,
      targetCursor: { line: 7, col: 0 },
      par: 1,
      hint: "G",
    },
    {
      kind: "challenge",
      id: "05-gg",
      instruction: "Jump back to the first line with `gg`.",
      startText: CODE,
      startCursor: { line: 6, col: 2 },
      targetText: CODE,
      targetCursor: { line: 0, col: 0 },
      par: 2,
      hint: "gg",
    },
    {
      kind: "challenge",
      id: "05-nG",
      instruction: "Jump straight to line 6 (`function main`) with a count + `G`.",
      startText: CODE,
      startCursor: { line: 0, col: 0 },
      targetText: CODE,
      targetCursor: { line: 5, col: 0 },
      par: 2,
      hint: "6G",
    },
  ],
};
