import type { Lesson } from "./types";

const CODE = 'const config = require("./config.json");';

export const lesson: Lesson = {
  id: "06-find-on-line",
  title: "Find on Line (f t F T ; ,)",
  section: "Motions",
  order: 6,
  steps: [
    {
      kind: "explanation",
      text: "`f{char}` jumps forward onto the next occurrence of a character in the line; `F{char}` searches backward. `t{char}` stops just **before** the character. `;` repeats the last find in the same direction, `,` repeats it the other way.",
    },
    {
      kind: "challenge",
      id: "06-f-equals",
      instruction: "Jump onto the `=` with `f`.",
      startText: CODE,
      startCursor: { line: 0, col: 0 },
      targetText: CODE,
      targetCursor: { line: 0, col: 13 },
      par: 2,
      hint: "f=",
    },
    {
      kind: "challenge",
      id: "06-f-semi",
      instruction: "Jump onto the `;` at the end of the line with `f`.",
      startText: CODE,
      startCursor: { line: 0, col: 0 },
      targetText: CODE,
      targetCursor: { line: 0, col: 39 },
      par: 2,
      hint: "f;",
    },
    {
      kind: "challenge",
      id: "06-second-o",
      instruction: "Jump onto the **second** `o` using `f` and `;`.",
      startText: CODE,
      startCursor: { line: 0, col: 0 },
      targetText: CODE,
      targetCursor: { line: 0, col: 7 },
      par: 3,
      hint: "fo then ;",
    },
    {
      kind: "challenge",
      id: "06-t-quote",
      instruction: "Jump to just **before** the first `\"` using `t`.",
      startText: CODE,
      startCursor: { line: 0, col: 0 },
      targetText: CODE,
      targetCursor: { line: 0, col: 22 },
      par: 2,
      hint: 't"',
    },
    {
      kind: "challenge",
      id: "06-F-paren",
      instruction: "From the end of the line, jump back onto the `(` with `F`.",
      startText: CODE,
      startCursor: { line: 0, col: 39 },
      targetText: CODE,
      targetCursor: { line: 0, col: 22 },
      par: 2,
      hint: "F(",
    },
    {
      kind: "challenge",
      id: "06-third-n",
      instruction: "Jump onto the **third** `n` using `f` and `;`.",
      startText: CODE,
      startCursor: { line: 0, col: 0 },
      targetText: CODE,
      targetCursor: { line: 0, col: 28 },
      par: 4,
      hint: "fn ; ;",
    },
  ],
};
