import type { Lesson } from "./types";

export const lesson: Lesson = {
  id: "08-deleting",
  title: "Deleting (x dd dw D + counts)",
  section: "Editing",
  order: 8,
  steps: [
    {
      kind: "explanation",
      text: "`x` deletes the character under the cursor. `dw` deletes to the start of the next word, `dd` deletes the whole line, `D` deletes from the cursor to the end of the line. Prefix any of them with a count: `3x`, `2dd`, `d3w`.",
    },
    {
      kind: "challenge",
      id: "08-x",
      instruction: "Delete the stray `x` under the cursor.",
      startText: "hxello",
      startCursor: { line: 0, col: 1 },
      targetText: "hello",
      par: 1,
      hint: "x",
    },
    {
      kind: "challenge",
      id: "08-3x",
      instruction: "Delete the three stray `a`s with a count.",
      startText: "aaahello",
      startCursor: { line: 0, col: 0 },
      targetText: "hello",
      par: 2,
      hint: "3x",
    },
    {
      kind: "challenge",
      id: "08-dw",
      instruction: "The word `the` is duplicated. Delete one of them with `dw`.",
      startText: "the the quick fox",
      startCursor: { line: 0, col: 0 },
      targetText: "the quick fox",
      par: 2,
      hint: "dw — deletes the word and the space after it",
    },
    {
      kind: "challenge",
      id: "08-dd",
      instruction: "Delete the middle line with `dd`.",
      startText: "keep this\ndelete this line\nkeep that",
      startCursor: { line: 1, col: 0 },
      targetText: "keep this\nkeep that",
      par: 2,
      hint: "dd",
    },
    {
      kind: "challenge",
      id: "08-2dd",
      instruction: "Delete both junk lines with one command (count + `dd`).",
      startText: "keep top\nold junk one\nold junk two\nkeep bottom",
      startCursor: { line: 1, col: 0 },
      targetText: "keep top\nkeep bottom",
      par: 3,
      hint: "2dd",
    },
    {
      kind: "challenge",
      id: "08-D",
      instruction: "Delete from the cursor to the end of the line with `D`.",
      startText: "const x = 1; // remove this comment",
      startCursor: { line: 0, col: 12 },
      targetText: "const x = 1;",
      par: 1,
      hint: "D",
    },
    {
      kind: "challenge",
      id: "08-d3w",
      instruction: "Delete the first three words with one command.",
      startText: "one two three four five",
      startCursor: { line: 0, col: 0 },
      targetText: "four five",
      par: 3,
      hint: "d3w",
    },
  ],
};
