import type { Lesson } from "./types";

export const lesson: Lesson = {
  id: "09-change-yank-put",
  title: "Change, Yank, Put (c y p P)",
  section: "Editing",
  order: 9,
  steps: [
    {
      kind: "explanation",
      text: "`c` (change) deletes and drops you into insert mode: `cw` changes a word, `cc` a whole line, `C` to the end of the line. `y` (yank) copies: `yy` copies a line. `p` pastes after the cursor/line, `P` before. Deletes also fill the paste buffer — `dd` + `p` moves a line.",
    },
    {
      kind: "challenge",
      id: "09-cw",
      instruction: "Change `slow` to `fast` with `cw`.",
      startText: "const speed = slow;",
      startCursor: { line: 0, col: 14 },
      targetText: "const speed = fast;",
      requireNormal: true,
      par: 7,
      hint: "cw fast <Esc>",
    },
    {
      kind: "challenge",
      id: "09-cc",
      instruction: "Replace the whole line with `right` using `cc`.",
      startText: "totally wrong line",
      startCursor: { line: 0, col: 8 },
      targetText: "right",
      requireNormal: true,
      par: 8,
      hint: "cc right <Esc>",
    },
    {
      kind: "challenge",
      id: "09-C",
      instruction: "Change everything from the cursor to the end of the line to `newValue;`.",
      startText: "let name = oldValue;",
      startCursor: { line: 0, col: 11 },
      targetText: "let name = newValue;",
      requireNormal: true,
      par: 11,
      hint: "C newValue; <Esc>",
    },
    {
      kind: "challenge",
      id: "09-yyp",
      instruction: "Duplicate the line with `yy` and `p`.",
      startText: "copy me",
      startCursor: { line: 0, col: 0 },
      targetText: "copy me\ncopy me",
      par: 3,
      hint: "yyp",
    },
    {
      kind: "challenge",
      id: "09-ddp",
      instruction: "These lines are in the wrong order. Swap them with `dd` and `p`.",
      startText: "second\nfirst",
      startCursor: { line: 0, col: 0 },
      targetText: "first\nsecond",
      par: 3,
      hint: "ddp — delete the first line, paste it below the other",
    },
  ],
};
