import type { Lesson } from "./types";

export const lesson: Lesson = {
  id: "13-text-objects",
  title: "Text Objects (iw aw i\" i( ip it)",
  section: "Text objects & Visual mode",
  order: 13,
  steps: [
    {
      kind: "explanation",
      text: "Text objects describe **what's around the cursor**: `iw` = inner word, `aw` = a word (with its space), `i\"` = inside quotes, `a\"` = quotes included, `i(` = inside parens, `ip` = inner paragraph, `it` = inside an HTML tag. Combine with any operator — and the cursor can be **anywhere inside** the object.",
    },
    {
      kind: "challenge",
      id: "13-diw",
      instruction: "Delete the word `BAD` (just the word) with `diw`.",
      startText: "one BAD three",
      startCursor: { line: 0, col: 5 },
      targetText: "one  three",
      par: 3,
      hint: "diw — note the double space left behind",
    },
    {
      kind: "challenge",
      id: "13-daw",
      instruction: "Delete the word `BAD` **and** its trailing space with `daw`.",
      startText: "one BAD three",
      startCursor: { line: 0, col: 5 },
      targetText: "one three",
      par: 3,
      hint: "daw",
    },
    {
      kind: "challenge",
      id: "13-ci-quote",
      instruction: "Fix the typo inside the quotes: change `wrold` to `world` with `ci\"`.",
      startText: 'greet("wrold");',
      startCursor: { line: 0, col: 9 },
      targetText: 'greet("world");',
      requireNormal: true,
      par: 9,
      hint: 'ci" world <Esc>',
    },
    {
      kind: "challenge",
      id: "13-ci-paren",
      instruction: "Replace all the arguments with `4, 5` using `ci(`.",
      startText: "sum(1, 2, 3)",
      startCursor: { line: 0, col: 7 },
      targetText: "sum(4, 5)",
      requireNormal: true,
      par: 8,
      hint: "ci( 4, 5 <Esc>",
    },
    {
      kind: "challenge",
      id: "13-da-paren",
      instruction: "Delete the parentheses and everything inside them with `da(`.",
      startText: "keep(remove this)",
      startCursor: { line: 0, col: 8 },
      targetText: "keep",
      par: 3,
      hint: "da(",
    },
    {
      kind: "challenge",
      id: "13-dip",
      instruction: "Delete the middle paragraph with `dip`.",
      startText: "keep above\n\ndel one\ndel two\n\nkeep below",
      startCursor: { line: 2, col: 1 },
      targetText: "keep above\n\n\nkeep below",
      par: 3,
      hint: "dip",
    },
    {
      kind: "challenge",
      id: "13-cit",
      instruction: "Change the text inside the tag to `new` with `cit`.",
      startText: "<b>old text</b>",
      startCursor: { line: 0, col: 5 },
      targetText: "<b>new</b>",
      requireNormal: true,
      par: 7,
      hint: "cit new <Esc>",
    },
  ],
};
