import type { Lesson } from "./types";

export const lesson: Lesson = {
  id: "18-capstone",
  title: "Capstone: Combined Workflows",
  section: "Power features",
  order: 18,
  steps: [
    {
      kind: "explanation",
      text: "Everything at once. Each challenge here is a realistic edit that combines skills from the whole course. Pars are the honest optimum — match them if you can, but solving at all is the win.",
    },
    {
      kind: "challenge",
      id: "18-rename",
      instruction: "Rename `spd` to `speed` at **all three** sites: `*` to prime the search, `cw` to change, then `n` and `.` to finish the rest.",
      startText: "let spd = 10;\nmove(spd);\nlog(spd);",
      startCursor: { line: 0, col: 4 },
      targetText: "let speed = 10;\nmove(speed);\nlog(speed);",
      requireNormal: true,
      par: 13,
      hint: "* cw speed <Esc> n . n .",
    },
    {
      kind: "challenge",
      id: "18-args",
      instruction: "Replace the argument list with `dark, light` in one text-object edit.",
      startText: "render(oldTheme, oldMode)",
      startCursor: { line: 0, col: 10 },
      targetText: "render(dark, light)",
      requireNormal: true,
      par: 14,
      hint: "ci( dark, light <Esc>",
    },
    {
      kind: "challenge",
      id: "18-comment-block",
      instruction: "Comment out all three lines at once: block-select the first column, then block-insert `//`.",
      startText: "alpha();\nbeta();\ngamma();",
      startCursor: { line: 0, col: 0 },
      targetText: "//alpha();\n//beta();\n//gamma();",
      requireNormal: true,
      par: 7,
      hint: "<C-v> j j I // <Esc>",
    },
    {
      kind: "challenge",
      id: "18-dedupe",
      instruction: "The title line is duplicated. Delete the duplicate.",
      startText: "title\ntitle\nbody text",
      startCursor: { line: 0, col: 0 },
      targetText: "title\nbody text",
      par: 3,
      hint: "j dd",
    },
    {
      kind: "challenge",
      id: "18-quote-fix",
      instruction: "Convert the single quotes to double quotes using `f` and `r`.",
      startText: "print('hello')",
      startCursor: { line: 0, col: 0 },
      targetText: 'print("hello")',
      par: 8,
      hint: "f' r\" f' r\" — or ; instead of the second f'",
    },
  ],
};
